# -*- coding: utf-8 -*-
"""AI-Powered Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8OSJHjLu3vY9SRCCmKpdwk7WQrDRtNb
"""

!pip install transformers torch gradio

from transformers import pipeline
import gradio as gr

# Initialize the chatbot pipeline
chatbot = pipeline('text-generation', model='microsoft/DialoGPT-large')

def chat_with_bot(user_input):
    # Generate a response from the chatbot
    response = chatbot(user_input, max_length=100, num_return_sequences=1)
    return response[0]['generated_text']

# Define the Gradio interface
interface = gr.Interface(
    fn=chat_with_bot,
    inputs=gr.Textbox(lines=2, placeholder="Type your message here..."),
    outputs=gr.Textbox(),
    title="AI-Powered Chatbot",
    description="Chat with an AI model using DialoGPT."
)

# Launch the interface
interface.launch(share=True)

